### ISSUE TITLE
complete the controller template

### ISSUE THREAD

**Issue by rocambille** [wasthishelpful/barista#1]
complete the template src/main/resources/templates/barista/Controller.java

add methods for a BREAD on a given resource `foo`, following REST uniform interface (**note:** the controller here should be annotated with `@Controller` and not `@RestController`):

**browse:** `GET: /foos`
**description:** get a view of all foo resources

**read:** `GET: /foos/{id}`
**description:** get a view of the foo resource identified by `id`

**edit:** `GET: /foos/{id}/edit`
**description:** get a form to edit the foo resource identified by `id`

**update:** `PUT: /foos/{id}`
**description:** store the modified foo resource and return a redirection to its read endpoint

**add:** `GET: /foos/add`
**description:** get a form to create a new foo resource

**store:** `POST: /foos`
**description:** store the new foo resource and return a redirection to its read endpoint

**destroy:** `DELETE: /foos/{id}`
**description:** delete the foo resource identified by `id`, and return a redirection to `/foos`

**Comment by idl99** [comment]
I'd like to be assigned to this issue please

**Comment by Ikhiloya** [comment]
Can I take this one or work with the @idl99

**Comment by ghost** [comment]
Yep, i would like do this issue pleas.

**Comment by rocambille** [comment]
solved by #14
