### ISSUE TITLE
add dates to entity template

### ISSUE THREAD

**Issue by rocambille** [wasthishelpful/barista#26]
In `src/main/resources/templates/barista/Entity.java` add:

* date of creation: should be current timestamp (datetime?) by default
* date of last modification:  should be current timestamp (datetime?) by default, and current timestamp on update
* date of deletion (aka soft delete): should be null by default

Resource: https://dev.mysql.com/doc/refman/8.0/en/timestamp-initialization.html

**Comment by chathurabuddi** [comment]
May I work on this issue?

**Comment by rocambille** [comment]
> May I work on this issue?

yes you can :)

**Comment by chathurabuddi** [comment]
@wasthishelpful , please review #27

**Comment by rocambille** [comment]
I am experiencing issue when updating: the returned entity after save has a null creation timestamp.

After some tests, it turns out that's linked to the update process, not the entity. I will open an other issue to address the problem, but this one is solved thanks to your work :)
